---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: apicurio
    pod: apicurio
  name: apicurio
  namespace: test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: apicurio
      pod: apicurio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: apicurio
        pod: apicurio
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: info
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: kafka-kafka-bootstrap.test.svc:9092
        image: apicurio/apicurio-registry-kafkasql:2.2.4.Final
        imagePullPolicy: IfNotPresent
        name: apicurio
        ports:
        - containerPort: 8080
          name: private
          protocol: TCP
        resources:
          limits:
            cpu: 250m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: xjoin-search-api
      serviceAccountName: xjoin-search-api
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apicurio
  name: apicurio
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      name: cluster
    - port: 1080
      protocol: TCP
      targetPort: 8080
      name: external
  selector:
    app: apicurio
  sessionAffinity: None
  type: ClusterIP
