apiVersion: registry.apicur.io/v1
kind: ApicurioRegistry
metadata:
  name: example-apicurioregistry-kafkasql
spec:
  configuration:
    kafkasql:
      bootstrapServers: 'kafka-kafka-bootstrap.test.svc:9092'
    persistence: kafkasql