apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: xjoin-operator-xjoin-operator-leader-election-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: xjoin-operator
subjects:
  - kind: ServiceAccount
    name: default
    namespace: xjoin-operator-system
