# permissions for end users to view xjoinpipelines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: xjoinpipeline-viewer-role
rules:
- apiGroups:
  - xjoin.cloud.redhat.com
  resources:
  - xjoinpipelines
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - xjoin.cloud.redhat.com
  resources:
  - xjoinpipelines/status
  verbs:
  - get
