apiVersion: v1
kind: Template
metadata:
  name: xjoin

objects:
  - apiVersion: v1
    data:
      endpoint: aHR0cDovL3hqb2luLWVsYXN0aWNzZWFyY2gtZXMtZGVmYXVsdC50ZXN0LnN2Yzo5MjAw
      username: eGpvaW4=
      password: eGpvaW4xMzM3
    kind: Secret
    metadata:
      name: xjoin-elasticsearch
    type: Opaque

  - apiVersion: elasticsearch.k8s.elastic.co/v1
    kind: Elasticsearch
    metadata:
      name: xjoin-elasticsearch
    spec:
      http:
        service:
          metadata:
            creationTimestamp: null
          spec: {}
        tls:
          selfSignedCertificate:
            disabled: true
      version: 7.13.0
      nodeSets:
        - name: default
          count: 1
          config:
            node.store.allow_mmap: false

  - apiVersion: xjoin.cloud.redhat.com/v1alpha1
    kind: XJoinPipeline
    metadata:
      name: xjoinpipeline
    spec:
      pause: false
      ephemeral: true

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-from-xjoin-operator-namespace
    spec:
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  kubernetes.io/metadata.name: xjoin
      podSelector: {}
      policyTypes:
        - Ingress