apiVersion: xjoin.cloud.redhat.com/v1alpha1
kind: XJoinIndex
metadata:
  name: test
spec:
  pause: false
  avroSchema: >
    {
      "type": "record",
      "name": "testindex",
      "xjoin.index": true,
      "fields": [{
        "xjoin.type": "reference",
        "type": "xjoindatasourcepipeline.test.Value",
        "name": "host"
      }]
    }