apiVersion: xjoin.cloud.redhat.com/v1alpha1
kind: XJoinPipeline
metadata:
  name: xjoinpipeline-sample
spec:
  # Add fields here
  connectCluster: xjoin-kafka-connect-strimzi
  elasticSearchURL: https://elasticsearch:9200
