apiVersion: xjoin.cloud.redhat.com/v1alpha1
kind: XJoinIndex
metadata:
  name: test
spec:
  pause: false
  avroSchema: >
    {
      "type": "record",
      "name": "testindex",
      "fields": [{
        "xjoin.type": "reference",
        "type": "xjoin.datasource.test",
        "name": "host"
      }]
    }