---
apiVersion: v1
kind: Service
metadata:
  name: ksql-server
  labels:
    app: ksql-server
spec:
  ports:
    - port: 8088
  selector:
    app: ksql-server

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksql-server
  labels:
    app: ksql-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksql-server
  template:
    metadata:
      labels:
        app: ksql-server
    spec:
      containers:
        - name: ksql-server
          image: confluentinc/ksqldb-server:0.20.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: server
              containerPort: 8088
          resources:
            limits:
              cpu: "1"
              memory: 2Gi
            requests:
              cpu: 100m
              memory: 128Mi
          env:
            - name: KSQL_BOOTSTRAP_SERVERS
              value: PLAINTEXT://kafka-kafka-bootstrap.test.svc:9092
            - name: KSQL_KSQL_SERVICE_ID
              value: ksql
            - name: KSQL_KSQL_SCHEMA_REGISTRY_URL
              value: http://example-apicurioregistry-kafkasql-service.test.svc:8080
            - name: KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE
              value: "true"
            - name: KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE
              value: "true"