# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/xjoin.cloud.redhat.com_xjoinpipelines.yaml
- bases/xjoin.cloud.redhat.com_xjoinindices.yaml
- bases/xjoin.cloud.redhat.com_xjoindatasources.yaml
- bases/xjoin.cloud.redhat.com_xjoindatasourcepipelines.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_xjoinpipelines.yaml
#- patches/webhook_in_xjoindatasources.yaml
#- patches/webhook_in_xjoindatasourcepipelines.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_xjoinpipelines.yaml
#- patches/cainjection_in_xjoindatasources.yaml
#- patches/cainjection_in_xjoindatasourcepipelines.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
